// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"context"
	"github.com/goplus/mcp/server"
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/qiniu/x/stringutil"
)

const _ = true

type hello struct {
	server.ToolApp
	*MCPApp
}
type MCPApp struct {
	server.MCPApp
}
//line demo/hello/main_mcp.gox:1
func (this *MCPApp) MainEntry() {
//line demo/hello/main_mcp.gox:1:1
	this.Server("Tool Demo 🚀", "1.0.0")
}
func (this *MCPApp) Main() {
	_xgo_obj0 := &hello{MCPApp: this}
	_xgo_lst1 := []server.ToolProto{_xgo_obj0}
	server.XGot_MCPApp_Main(this, nil, _xgo_lst1, nil)
}
//line demo/hello/hello_tool.gox:1
func (this *hello) Main(_xgo_arg0 context.Context, _xgo_arg1 mcp.CallToolRequest, _xgo_arg2 *server.ToolAppProto) mcp.Content {
	this.ToolApp.Main(_xgo_arg0, _xgo_arg1, _xgo_arg2)
//line demo/hello/hello_tool.gox:1:1
	this.Tool("helloWorld", func() {
//line demo/hello/hello_tool.gox:2:1
		this.Description("Say hello to someone")
//line demo/hello/hello_tool.gox:3:1
		this.String("name", func() {
//line demo/hello/hello_tool.gox:4:1
			this.Required()
//line demo/hello/hello_tool.gox:5:1
			this.Description("Name of the person to greet")
		})
	})
//line demo/hello/hello_tool.gox:9:1
	name, ok := this.XGo_Env("name").(string)
//line demo/hello/hello_tool.gox:10:1
	if !ok {
//line demo/hello/hello_tool.gox:11:1
		return server.NewError__0("name must be a string")
	}
//line demo/hello/hello_tool.gox:14:1
	return server.Text__0(stringutil.Concat("Hello, ", name, "!"))
}
func (this *hello) Classclone() server.ToolProto {
	_xgo_ret := *this
	return &_xgo_ret
}
func main() {
	new(MCPApp).Main()
}
