// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"github.com/goplus/mcp/mtest"
	"testing"
)

type case_calc struct {
	mtest.CaseApp
}
//line demo/calc/calc_mtest.gox:1
func (this *case_calc) Main() {
//line demo/calc/calc_mtest.gox:1:1
	this.TestServer__0(new(MCPApp))
//line demo/calc/calc_mtest.gox:3:1
	this.Initialize(nil)
//line demo/calc/calc_mtest.gox:4:1
	this.RetWith(map[string]interface{}{})
//line demo/calc/calc_mtest.gox:6:1
	this.Call__0("mul", map[string]any{"x": 2, "y": 3})
//line demo/calc/calc_mtest.gox:7:1
	this.RetWith(map[string][]map[string]string{"content": []map[string]string{map[string]string{"text": "multiply result:", "type": "text"}, map[string]string{"text": "6", "type": "text"}}})
}
func Test_calc(t *testing.T) {
	mtest.Gopt_CaseApp_TestMain(new(case_calc), t)
}
