// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"github.com/goplus/mcp/mtest"
	"testing"
)

type case_user_profile struct {
	mtest.CaseApp
}
//line demo/resource/user_profile_mtest.gox:1
func (this *case_user_profile) Main() {
//line demo/resource/user_profile_mtest.gox:1:1
	this.TestServer__0(new(MCPApp))
//line demo/resource/user_profile_mtest.gox:3:1
	this.Initialize(nil)
//line demo/resource/user_profile_mtest.gox:4:1
	this.RetWith(map[string]interface{}{})
//line demo/resource/user_profile_mtest.gox:6:1
	this.Read("users://123/profile", nil)
//line demo/resource/user_profile_mtest.gox:7:1
	this.RetWith(map[string][]map[string]string{"contents": []map[string]string{map[string]string{"mimeType": "application/json", "text": `{"age":15,"id":"123","name":"Ken"}`, "uri": "users://123/profile"}}})
}
func Test_user_profile(t *testing.T) {
	mtest.Gopt_CaseApp_TestMain(new(case_user_profile), t)
}
